Added a bunch of docstrings, mainly for the cog processing chain
Deadwood-ai/deadwood-api pull request #18
Opened 2024-07-31 22:47 UTC by lucfr

be aware: contains one potentially breaking change (9f33a1068f9bd9818d4e2a6d1b89a36d2b50bc47)

2024-08-01 10:10 UTC, mmaelicke requested changes
Thanks a lot!. There is only a minor change request.

2024-08-01 10:10 UTC, mmaelicke commented on src/routers/cog.py
> +    calculating in the background.
to be more precise: It adds the task to the background process of FastAPI. The task metadata is returned to inform the user on the frontend about the queue position and estimated wait time

2024-08-02 10:36 UTC, lucfr commented
@mmaelicke 1fd7cd814585bb18ffb014339d322e0aeb948384 hopefully fixes your comments

2024-08-02 10:44 UTC, mmaelicke approved these changes
Nice, Thanks a lot!

2024-08-02 10:44 UTC, merged